version: "3.6"

networks:
  redpanda_network:
    driver: bridge
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.13
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
    ports:
      - 19092:19092
      - 19644:9644
      - 18082:18082
      - 18081:18081
    networks:
      - redpanda_network
    volumes:
      - ./redpanda:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy: +true' || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 5
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8300:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
     - ./kui/config.yaml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - redpanda_network
